apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "certificate-app-deployer.fullname" . }}
  labels:
    {{- include "certificate-app-deployer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "certificate-app-deployer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "certificate-app-deployer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "certificate-app-deployer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.config.env }}
          env:
          {{- range $key, $value := .Values.config.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if and .Values.config.envFromSecret (not .Values.config.secretsStore.enabled) }}
          envFrom:
            - secretRef:
                name: {{ include "certificate-app-deployer.secretName" . }}
          {{- end }}
          {{- if and (and (and (empty .Values.config.envFromSecret) .Values.config.secretsStore.enabled) .Values.config.secretsStore.name) .Values.config.secretsStore.providerClass }}
          envFrom:
            - secretRef:
                name: {{ .Values.config.secretsStore.name }}
          {{- end }}
          volumeMounts:
          {{- if and (and (and (empty .Values.config.envFromSecret) .Values.config.secretsStore.enabled) .Values.config.secretsStore.name) .Values.config.secretsStore.providerClass }}
            - name: secrets-store
              mountPath: "/var/secrets"
              readOnly: true
          {{- end }}
          {{- if .Values.config.data.enabled }}
            - name: data
              mountPath: {{ .Values.config.data.path }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.startupProbe.path }}
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          {{- end }}
          {{- if .Values.livenessProbe.path }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          {{- end }}
          {{- if .Values.livenessProbe.path }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if and (and (and (empty .Values.config.envFromSecret) .Values.config.secretsStore.enabled) .Values.config.secretsStore.name) .Values.config.secretsStore.providerClass }}
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.config.secretsStore.providerClass }}
      {{- end }}
      {{- if .Values.config.data.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "certificate-app-deployer.fullname" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
